=== Deloitte-VA/snp-prototype/lego/src/main/xsd/LEGO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Version 2013/08/20 -->
<!-- 
	Changelog:
	8/20/13 - Added PNCS Value Field to the allowed measurementConstants
	3/06/13	- Removed unnecessary enum values.
	1/17/13	- Changing the wording of the measurementConstants to be more user friendly.
	1/15	- Changed point from a float to a double and allowed to to be a double or a long.  Also changed the way it is structured, 
				so that the generated java code uses inheritance, instead of a choice (closer alignment to sim-api which uses Number, 
				but that can't be mapped from XML - double or long should let us hold anything we need to)
	1/10	- Reorganized Bound and Interval under measurement to better align with the sim-api.  No changes to what is representable.
				Got rid of timing node, which served no purpose (moved measurement up a level under the assertion)
	1/8		- Getting rid of the unnecessary assertionComponents field.  Allowed the assertionComponent in assertion to be an unbounded
				list instead of a single reference instead.
	1/4		- Added (optional) comment fields to the Lego and the Lego List.
	12/14	- Got rid of 'expressionConjuction' - no longer necessary now that we have the 'expression' type.
	12/13	- Moved relationships from concept to a new type 'expression'.  'discernible', 'qualifier', 'value' and 'destination'
				have their target types changed to 'expression'.  'type' and 'units' remain as concept - so type and units can no longer
				have nested rels.
			- Renamed 'conceptConjunction' to 'expressionConjunction'.  Reordered the elements within for consistency.
	12/07	- Renamed 'rel' to 'relation' for consistency.  
			- Added 'relationGroup' as a possible target of 'concept', instead of just 'relation'.  
			- Created 'conceptConjunction' - added as a possible target for 'discernible', 'qualifier', 'value', 'destination'
			- Created 'boolean' and 'text' as new types - can be used within a 'value' or a 'destination'
			- Renamed 'stringValue' to 'stringConstant' within 'point' to make it more clear, help differentiate from the new literal
				'text' type which allows any string.
	11/28	- removed minOccur=0 from measurement in timing - it didn't make sense.  If you have a timing, you need a measurement.
	11/26	- added a UUID to the stamp for lego editor sanity - otherwise, there was nothing to define a unique lego.  
				Now, stampUUID + legoUUID is globally unique.
 -->

	<xs:element name="legoList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="groupName" type="xs:string" />
				<xs:element name="legoListUUID" type="UUID" />
				<xs:element name="groupDescription" type="xs:string" minOccurs="0" />
				<xs:element name="comment" type="xs:string" minOccurs="0" />
				<xs:element ref="lego" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lego">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="legoUUID" type="UUID" />
				<xs:element ref="stamp" />
				<xs:element ref="pncs" />
				<xs:element ref="assertion" minOccurs="1" maxOccurs="unbounded" />
				<xs:element name="comment" type="xs:string" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="assertion">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="assertionUUID" type="UUID" />
				<xs:element ref="discernible" />
				<xs:element ref="qualifier" />
				<xs:element ref="value" />
				<xs:element name="timing" type="measurement" minOccurs="0" />
				<xs:element ref="assertionComponent" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="UUID">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="pncs">
		<xs:complexType>
			<xs:attribute name="id" use="required" type="xs:int" />
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="value" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="assertionComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="assertionUUID" type="UUID"/>
				<xs:element ref="type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="type">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="expression">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="concept"/>
					<xs:element ref="expression" minOccurs="2" maxOccurs="unbounded"/>
				</xs:choice>
				<xs:element ref="relation" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="relationGroup" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="concept">
		<xs:complexType>
			<xs:attribute name="sctid" use="optional" type="xs:long" />  <!-- Ideally, I would say that at least one of the IDs must exist, but there isn't a good way to do that in schema -->
			<xs:attribute name="uuid" use="optional" type="UUID" />
			<xs:attribute name="desc" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="discernible">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="expression"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="expression"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="expression"/>
					<xs:element ref="text" />
					<xs:element ref="boolean" />
					<xs:element name="measurement" type="measurement" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="relation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="destination"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="relationGroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="relation" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="destination">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="expression"/>
					<xs:element ref="text" />
					<xs:element ref="boolean" />
					<xs:element name="measurement" type="measurement"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="measurementConstant">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DOB" />
			<xs:enumeration value="NOW" />
			<xs:enumeration value="start active service" />
			<xs:enumeration value="end active service" />
			<xs:enumeration value="PNCS Value Field" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="text" type="xs:string"/>

    <xs:element name="boolean" type="xs:boolean"/>
    
	<xs:complexType name="measurement">
		<xs:sequence>
			<xs:element ref="units" minOccurs="0" maxOccurs="1" />
			<xs:choice>
				<xs:element name="point" type="point"/>
				<xs:element name="bound" type="bound" />
				<xs:element ref="interval" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bound">
		<xs:sequence>
			<!-- I'd like to define that at least one of these must exist, but when you do that the really cryptic way that xml schema requires, it makes the generated jaxb really ugly. -->
			<xs:element name="lowerPoint" type="point"  minOccurs="0"/>
			<xs:element name="upperPoint" type="point" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="lowerPointInclusive" type="xs:boolean"/>
		<xs:attribute name="upperPointInclusive" type="xs:boolean"/>
	</xs:complexType>

	<xs:element name="interval">
		<xs:complexType>
			<xs:sequence> 
				<!-- I'd like to define that at least one of these must exist, but when you do that the really cryptic way that xml schema requires, it makes the generated jaxb really ugly. -->
				<xs:element name="lowerBound" type="bound" minOccurs="0" />
				<xs:element name="upperBound" type="bound" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element >
	
	<xs:complexType name="point" abstract="true"/>
	
	<xs:complexType name="pointLong" >
		<xs:complexContent>
			<xs:extension base="point">
				<xs:sequence>
					<xs:element name="value" type="xs:long"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="pointDouble" >
		<xs:complexContent>
			<xs:extension base="point">
				<xs:sequence>
					<xs:element name="value" type="xs:double"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="pointMeasurementConstant" >
		<xs:complexContent>
			<xs:extension base="point">
				<xs:sequence>
					<xs:element name="value" type="measurementConstant"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="units">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="stamp">
		<xs:complexType>
			<xs:attribute name="status" use="optional" type="xs:string" />
			<xs:attribute name="time" use="optional" type="xs:dateTime" />
			<xs:attribute name="author" use="optional" type="xs:string" />
			<xs:attribute name="module" use="optional" type="xs:string" />
			<xs:attribute name="path" use="optional" type="xs:string" />
			<xs:attribute name="uuid" use="optional" type="UUID" />  <!--  Adding this for sanity in the GUI - uniquely identifies the stamp, this UUID plus lego UUID uniquely identifies a lego -->
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Deloitte-VA/snp-prototype/core/src/test/resources/testExpressionOneRelation.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<legoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="LEGO.xsd">
	<groupName>Hypertension Disability Benefits Questionnaire</groupName>
	<legoListUUID>7e277b2b-a6a7-47d5-aa34-73005aa88314</legoListUUID>
	<groupDescription>Legos about Hypertension</groupDescription>
	<comment></comment>
	<lego>
		<legoUUID>67390d97-055c-4d98-8113-67aef2c0be66</legoUUID>
        <stamp status="Active" time="2014-01-09T11:01:05.346-05:00" author="hsaitwal" module="default module" path="default path" uuid="2107d14e-43fa-40a1-ae59-ca8a06a0b943"/>
        <pncs id="29363" name="Medical history - Diagnosis of hypertension or isolated systolic hypertension confirmed by blood pressure (BP) readings taken 2 or more times on at least 3 different days - Yes - BP reading 1 and 2 - Date" value="Free text"/>
		<assertion>
			<assertionUUID>89cf1075-d7b1-48b0-95e1-9eb328c9dec7</assertionUUID>
			<discernible>
				<expression>
					<concept sctid="439272007" uuid="c909e67a-9925-3ebc-9e77-65227a329bea" desc="Date of procedure (observable entity)" />
					<relation>
						<type>
							<concept sctid="53" uuid="d82c8d16-19ad-3176-9665-453cfb2e55f0" desc="IS ABOUT (attribute)" />
						</type>
						<destination>
							<expression>
								<concept sctid="46973005" uuid="215fd598-e21d-3e27-a0a2-8e23b1b36dfc" desc="Blood pressure taking (procedure)" />
							</expression>
						</destination>
					</relation>
				</expression>
			</discernible>
			<qualifier>
				<expression>
					<concept sctid="108217004" uuid="ed2f734a-9196-3410-ae04-751808edf584" desc="Interview, history AND/OR physical examination (procedure)" />
				</expression>
			</qualifier>
			<value>
				<measurement>
					<point xsi:type="pointMeasurementConstant">
						<value>PNCS Value Field</value>
					</point>
				</measurement>
			</value>
		</assertion>
	</lego>
</legoList>

=== Deloitte-VA/snp-prototype/core/src/test/resources/testExpressionThreeRelations.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<legoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LEGO.xsd">
	<groupName>Audiology OBSERVABLES</groupName>
	<legoListUUID>530391c6-fe77-4638-ba99-1c33cae59ab5</legoListUUID>
	<groupDescription>Observables for new VA Audiology form</groupDescription>
	<comment></comment>
	<lego>
		<legoUUID>3d51bdd3-6c22-4763-b503-a50a18e89490</legoUUID>
		<stamp status="Active" time="2013-07-31T00:10:28.333-07:00" author="dsperzel" module="default module" path="default path" uuid="8da17010-acfd-4048-88ea-494d55c90559"/>
		<pncs id="101" name="Average hearing threshold in right ear" value="PNCS_VALUE_FIELD"/>
		<assertion>
			<assertionUUID>3ffb0d64-44d6-40ff-8fab-c549f1468c2b</assertionUUID>
			<discernible>
				<expression>
					<concept sctid="89269003" uuid="816a0a98-fc57-37a8-9581-83dc049d0189" desc="Threshold of hearing (observable entity)" />
					<relation>
						<type>
							<concept sctid="39" uuid="d67d8ab4-f4c1-3bf2-aaa3-53e27879133c" desc="PROPERTY TYPE (attribute)" />
						</type>
						<destination>
							<expression>
								<concept sctid="118589004" uuid="15e7eff2-66be-3502-8e54-d174e3139608" desc="Threshold (property) (qualifier value)" />
							</expression>
						</destination>
					</relation>
					<relation>
						<type>
							<concept sctid="36" uuid="19ca14e7-ea63-38a4-ae0e-b13d585e4c22" desc="INHERES IN (attribute)" />
						</type>
						<destination>
							<expression>
								<concept sctid="22945000" uuid="cfbb74be-3c4b-3b25-b571-e1f709859b6e" desc="Inner ear structure (body structure)" />
								<relation>
									<type>
										<concept sctid="272741003" uuid="26ca4590-bbe5-327c-a40a-ba56dc86996b" desc="Laterality (attribute)" />
									</type>
									<destination>
										<expression>
											<concept sctid="24028007" uuid="0b506040-5d71-3287-813a-d9e4d74d928b" desc="Right (qualifier value)" />
										</expression>
									</destination>
								</relation>
							</expression>
						</destination>
					</relation>
				</expression>
			</discernible>
			<qualifier>
				<expression>
					<concept sctid="252577008" uuid="6a66c427-650c-3401-adca-025c17c3933b" desc="Pure tone audiometry (procedure)" />
				</expression>
			</qualifier>
			<value>
				<measurement>
					<units>
						<concept sctid="259042002" uuid="4db394d1-a0a5-348e-9262-0b7c277021aa" desc="decibel (qualifier value)" />
					</units>
					<point xsi:type="pointLong">
						<value>-10000</value>
					</point>
				</measurement>
			</value>
		</assertion>
	</lego>
</legoList>

=== Deloitte-VA/snp-prototype/lego/src/test/resources/lego.xml
<?xml version="1.0" encoding="UTF-8"?>
<lego xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LEGO.xsd">
    <legoUUID>2601a0fa-3f0f-453c-9186-9ddf5dec3fd9</legoUUID>
    <stamp status="Active" time="2013-07-30T19:47:23.770-07:00" author="dsperzel" module="default module" path="default path" uuid="f681273f-d2f0-455a-bae2-0be1e83426d7"/>
    <pncs id="26274" name="Claim for tinnitus" value="Yes"/>
    <assertion>
        <assertionUUID>96cd1743-65e0-418c-958f-1a9215007299</assertionUUID>
        <discernible>
            <expression>
                <concept sctid="1217" uuid="6a61d423-d02a-3c56-a50d-c23ae7ff12f3" desc="VA benefit claim filed  (observable entity) "/>
                <relation>
                    <type>
                        <concept sctid="53" uuid="d82c8d16-19ad-3176-9665-453cfb2e55f0" desc="IS ABOUT (attribute)"/>
                    </type>
                    <destination>
                        <expression>
                            <concept sctid="155248003" uuid="abba4bbd-0223-3987-8b19-7ddd52e779b5" desc="Tinnitus (disorder)"/>
                        </expression>
                    </destination>
                </relation>
            </expression>
        </discernible>
        <qualifier>
            <expression>
                <concept sctid="108217004" uuid="ed2f734a-9196-3410-ae04-751808edf584" desc="Interview, history AND/OR physical examination (procedure)"/>
            </expression>
        </qualifier>
        <value>
            <expression>
                <concept sctid="373066001" uuid="c928767e-f519-3b34-bff2-a2ed3cd5c6c3" desc="Yes (qualifier value)"/>
            </expression>
        </value>
    </assertion>
</lego>

=== Deloitte-VA/snp-prototype/lego/src/test/resources/legolist.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<legoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LEGO.xsd">
    <groupName>Audiology OBSERVABLES</groupName>
    <legoListUUID>530391c6-fe77-4638-ba99-1c33cae59ab5</legoListUUID>
    <groupDescription>Observables for new VA Audiology form</groupDescription>
    <comment></comment>
    <lego>
        <legoUUID>2601a0fa-3f0f-453c-9186-9ddf5dec3fd9</legoUUID>
        <stamp status="Active" time="2013-07-30T19:47:23.770-07:00" author="dsperzel" module="default module" path="default path" uuid="f681273f-d2f0-455a-bae2-0be1e83426d7"/>
        <pncs id="26274" name="Claim for tinnitus" value="Yes"/>
        <assertion>
            <assertionUUID>96cd1743-65e0-418c-958f-1a9215007299</assertionUUID>
            <discernible>
                <expression>
                    <concept sctid="1217" uuid="6a61d423-d02a-3c56-a50d-c23ae7ff12f3" desc="VA benefit claim filed  (observable entity) "/>
                    <relation>
                        <type>
                            <concept sctid="53" uuid="d82c8d16-19ad-3176-9665-453cfb2e55f0" desc="IS ABOUT (attribute)"/>
                        </type>
                        <destination>
                            <expression>
<concept sctid="155248003" uuid="abba4bbd-0223-3987-8b19-7ddd52e779b5" desc="Tinnitus (disorder)"/>
                            </expression>
                        </destination>
                    </relation>
                </expression>
            </discernible>
            <qualifier>
                <expression>
                    <concept sctid="108217004" uuid="ed2f734a-9196-3410-ae04-751808edf584" desc="Interview, history AND/OR physical examination (procedure)"/>
                </expression>
            </qualifier>
            <value>
                <expression>
                    <concept sctid="373066001" uuid="c928767e-f519-3b34-bff2-a2ed3cd5c6c3" desc="Yes (qualifier value)"/>
                </expression>
            </value>
        </assertion>
    </lego>
    <lego>
        <legoUUID>264ba329-f10f-4e98-bf2a-04a39ed629bf</legoUUID>
        <stamp status="Active" time="2013-07-30T19:53:07.808-07:00" author="dsperzel" module="default module" path="default path" uuid="b8f84c65-06e1-4418-8633-03f8bd4ba2b9"/>
        <pncs id="26274" name="Claim for tinnitus" value="No"/>
        <assertion>
            <assertionUUID>da89cc8e-265f-4029-bf6c-9aeedfca9782</assertionUUID>
            <discernible>
                <expression>
                    <concept sctid="1217" uuid="6a61d423-d02a-3c56-a50d-c23ae7ff12f3" desc="VA benefit claim filed  (observable entity) "/>
                    <relation>
                        <type>
                            <concept sctid="53" uuid="d82c8d16-19ad-3176-9665-453cfb2e55f0" desc="IS ABOUT (attribute)"/>
                        </type>
                        <destination>
                            <expression>
<concept sctid="155248003" uuid="abba4bbd-0223-3987-8b19-7ddd52e779b5" desc="Tinnitus (disorder)"/>
                            </expression>
                        </destination>
                    </relation>
                </expression>
            </discernible>
            <qualifier>
                <expression>
                    <concept sctid="108217004" uuid="ed2f734a-9196-3410-ae04-751808edf584" desc="Interview, history AND/OR physical examination (procedure)"/>
                </expression>
            </qualifier>
            <value>
                <expression>
                    <concept sctid="373067005" uuid="d58a8003-b801-3da2-83c1-e09497c9bb53" desc="No (qualifier value)"/>
                </expression>
            </value>
        </assertion>
    </lego>
</legoList>
